// Code generated by "stringer -type=AuthType -trimprefix=AuthType types.go"; DO NOT EDIT.

package authtypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthTypeUnknown-0]
	_ = x[AuthTypeNone-1]
	_ = x[AuthTypeQueryString-2]
	_ = x[AuthTypeAuthHeader-3]
}

const _AuthType_name = "UnknownNoneQueryStringAuthHeader"

var _AuthType_index = [...]uint8{0, 7, 11, 22, 32}

func (i AuthType) String() string {
	if i < 0 || i >= AuthType(len(_AuthType_index)-1) {
		return "AuthType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthType_name[_AuthType_index[i]:_AuthType_index[i+1]]
}
