// Code generated by "stringer -type=STSOperation apiactions.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownOperation-0]
	_ = x[AssumeRoleWithWebIdentity-1]
}

const _STSOperation_name = "UnknownOperationAssumeRoleWithWebIdentity"

var _STSOperation_index = [...]uint8{0, 16, 41}

func (i STSOperation) String() string {
	if i < 0 || i >= STSOperation(len(_STSOperation_index)-1) {
		return "STSOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _STSOperation_name[_STSOperation_index[i]:_STSOperation_index[i+1]]
}
