// Code generated by "stringer -type=S3Capability -trimprefix=S3Capability backend-s3-capabilities.go"; DO NOT EDIT.

package interfaces

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[S3CapabilityStreamingUnsignedPayloadTrailer-0]
}

const _S3Capability_name = "StreamingUnsignedPayloadTrailer"

var _S3Capability_index = [...]uint8{0, 31}

func (i S3Capability) String() string {
	if i < 0 || i >= S3Capability(len(_S3Capability_index)-1) {
		return "S3Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _S3Capability_name[_S3Capability_index[i]:_S3Capability_index[i+1]]
}
