// Code generated by "stringer -type=AWSErrorCode -trimprefix=Err shared-errors.go"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrAWSNone-0]
	_ = x[ErrAWSInternalError-1]
	_ = x[ErrAWSInvalidSignature-2]
	_ = x[ErrAWSAccessDenied-3]
	_ = x[ErrInvalidAccessKeyId-4]
	_ = x[ErrAuthorizationHeaderMalformed-5]
}

const _AWSErrorCode_name = "AWSNoneAWSInternalErrorAWSInvalidSignatureAWSAccessDeniedInvalidAccessKeyIdAuthorizationHeaderMalformed"

var _AWSErrorCode_index = [...]uint8{0, 7, 23, 42, 57, 75, 103}

func (i AWSErrorCode) String() string {
	if i < 0 || i >= AWSErrorCode(len(_AWSErrorCode_index)-1) {
		return "AWSErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AWSErrorCode_name[_AWSErrorCode_index[i]:_AWSErrorCode_index[i+1]]
}
