// Code generated by "stringer -type=S3Operation apiactions.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownOperation-0]
	_ = x[ListObjectsV2-1]
	_ = x[GetObject-2]
	_ = x[ListBuckets-3]
	_ = x[HeadBucket-4]
	_ = x[HeadObject-5]
	_ = x[PutObject-6]
	_ = x[CreateMultipartUpload-7]
	_ = x[CompleteMultipartUpload-8]
	_ = x[AbortMultipartUpload-9]
	_ = x[UploadPart-10]
}

const _S3Operation_name = "UnknownOperationListObjectsV2GetObjectListBucketsHeadBucketHeadObjectPutObjectCreateMultipartUploadCompleteMultipartUploadAbortMultipartUploadUploadPart"

var _S3Operation_index = [...]uint8{0, 16, 29, 38, 49, 59, 69, 78, 99, 122, 142, 152}

func (i S3Operation) String() string {
	if i < 0 || i >= S3Operation(len(_S3Operation_index)-1) {
		return "S3Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _S3Operation_name[_S3Operation_index[i]:_S3Operation_index[i+1]]
}
