name: pre-commit

on:
  pull_request:
    branches: [ "*", "**" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: staticcheckinstall
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: gosecinstall
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest
    # - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
